#! /bin/sh
#
# crankinit Initialize the sbengine for Crank
#

case "$1" in
 start)
                echo "Starting sbengine..."
                if [ -f /etc/profile.d/tslib.sh ]; then
                        source /etc/profile.d/tslib.sh
                fi              
                export SB_PLUGINS=/Crank/plugins/
                export LD_LIBRARY_PATH=/Crank/lib
                /Crank/bin/sbengine /application/src/circles.gapp &
                ;;
 debug)
                echo "Debugging sbengine..."
                if [ -f /etc/profile.d/tslib.sh ]; then
                        source /etc/profile.d/tslib.sh
                fi              
                export SB_PLUGINS=/Crank/plugins/
                export LD_LIBRARY_PATH=/Crank/lib
                /Crank/bin/sbengine -vvv /application/src/circles.gapp &
                ;;
 stop)
                echo "Stopping sbengine..."
                killall sbengine
 ;;
 *)
 echo "Usage: crankinit {start|stop}" >&2
 exit 1
 ;;
esac

exit 0
