#! /bin/sh
#
# crankinit	Initialize the sbengine for Crank
#

case "$1" in
	start|"")
		test "$VERBOSE" != no && echo "Initializing sbengine..."
                if [ -f /etc/profile.d/tslib.sh ]; then
                        source /etc/profile.d/tslib.sh
                fi  
                if [ -e "$TSLIB_TSDEVICE" ]; then
                        if [ ! -f /etc/pointercal ]; then
                                /usr/bin/ts_calibrate
                        fi  
                fi                 
                export GRE_PLUGINS=/usr/lib/plugin
                if [ ! -f /usr/lib/libts-0.0.so.0 ]; then
                  ln -s /usr/lib/libts-1.0.so.0 /usr/lib/libts-0.0.so.0
                fi
                /usr/bin/sbengine /application/crank-demo/button.gapp &
                ;;
	stop)
		test "$VERBOSE" != no && echo "Disabling sbengine..."
                killall sbengine
		;;
	*)
		echo "Usage: crankinit {start|stop}" >&2
		exit 1
		;;
esac

exit 0
